/* Automatically generated by './build/bin/build-entry.js' */

import ElTest from '../packages/element/test/index.js';
import VanTest from '../packages/vant/test/index.js';
import VanImage from '../packages/vant/image/index.js';
const components = [
  ElTest,
  VanTest,
  VanImage
]
const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};
/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  ElTest,
  VanTest,
  VanImage
};
