/* Automatically generated by './build/bin/build-entry.js' */

import ZtImage from '../packages/vant/image/index.js';
import ZtScrollRefresh from '../packages/vant/scroll-refresh/index.js';
const components = [
  ZtImage,
  ZtScrollRefresh
]
const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};
/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  ZtImage,
  ZtScrollRefresh
};
